### ISSUE TITLE
Stuck on chrome

### ISSUE THREAD

**Issue by rogerdue** [byteyilabs/yi-note#105]
it usually open and type the note, and hide it, now its stucked on the youtube page and can't hide it.

**Comment by Volker-brdb** [comment]
can confirm this...happens for me, too
YiNote v1.7.0
Chrome Version 95.0.4638.69 (Offizieller Build) (64-Bit)

**Comment by GlennOu66304** [comment]
Yes, if the developer can fix this bug or give a solution, would be appreciated a a lot.

**Comment by yuis-ice** [comment]
the same problem for me. It's on the latest brave.

**Comment by quentin-mckay** [comment]
Same issue for me. I'm on Chrome Version 99.0.4844.74 (Official Build) (64-bit)

**Comment by lemattma** [comment]
I've created a PR fixing this issue: https://github.com/shuowu/yi-note/pull/113

**Comment by shuowu** [comment]
Issue has been fixed and released in v1.8.1 in [chrome web store](https://chromewebstore.google.com/detail/yinote/fhpgggnmdlmekfdpkdgeiccfkignhkdf)
