### ISSUE TITLE
can you give a toggle button to make the panel show and display

### ISSUE THREAD

**Issue by akiritoa** [byteyilabs/yi-note#122]
I want a toggle button to make the panel show and display, otherwise I should write by myself

**Comment by WeberAlex** [comment]
And make the panel resizable so that I don't need to open a separate issue.

**Comment by WeberAlex** [comment]
duplicate of #106

**Comment by shuowu** [comment]
Panel toggle issue has been resolved and released in version 1.8.1 in [chrome web store](https://chromewebstore.google.com/detail/yinote/fhpgggnmdlmekfdpkdgeiccfkignhkdf)
