### ISSUE TITLE
Missing script : bootstrap

### ISSUE THREAD

**Issue by HananoshikaYomaru** [byteyilabs/yi-note#85]
Hello, @shuowu. First I want to thank you for this amazing browser extension for students. I am trying to add my own features to the extension but I am not familiar with Lerna. 

When I run `npm run bootstrap`, I see the following : 

```
npm ERR! missing script: bootstrap

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Yomaru/.npm/_logs/2021-03-03T02_46_29_456Z-debug.log
```

There is no such script in package.json named `bootstrap`. I wonder how can I solve this.

**Comment by shuowu** [comment]
I recently switched from lerna to yarn workspace (looks like i forgot to update the readme , sorry about that...)

You can run 'yarn install' under the root directory, then 'yarn start:ext' to start the extension development.

**Comment by HananoshikaYomaru** [comment]
Oh thx. Hope you have time to update the document in the next commit. Keep up the good work. : )

**Comment by supertedde** [comment]
I also struggled a bit with the instructions probably being slightly dated. This plugin carries significantly more merits than what's currently being reckognized. Great work!!! I'm not much of a developer any longer (more product mgmt focus), but may try to fix some things related to [bug 108](https://github.com/shuowu/yi-note/issues/108) which I recently added. Cheers!
